In [1]:
%matplotlib inline
import matplotlib.pyplot as plt 
import numpy as np
import pandas

import keras
from keras.layers import Dense, Activation, Conv2D, Dropout, Flatten, MaxPooling2D
from keras.optimizers import Adam
from keras.datasets import mnist
from keras.models import Sequential
from keras.utils import to_categorical



Using TensorFlow backend.


In [2]:
(x_train, y_train), (x_test, y_test) = mnist.load_data()

In [3]:
x0_train = x_train.copy()
y0_train = y_train.copy()
x0_test = x_test.copy()
y0_test = y_test.copy()

In [4]:
x_train = x_train/x_train.max()
x_test = x_test/x_test.max()

In [5]:
for i in range(len(y_train)):
    if y_train[i] %2 == 0:
        y_train[i]=0
    else :
        y_train[i]=1
        
for j in range(len(y_test)):
    if y_test[j] %2 == 0:
        y_test[j]=0
    else :
        y_test[j]=1


In [6]:
print (y_test)
print (y0_test)
print (y_train)
print (y0_train)

[1 0 1 ... 0 1 0]
[7 2 1 ... 4 5 6]
[1 0 0 ... 1 0 0]
[5 0 4 ... 5 6 8]


In [7]:
y_train = to_categorical(y_train, 2)
y_test = to_categorical(y_test, 2)

In [8]:
x_train = x_train.reshape((x_train.shape[0], 28, 28, -1))
x_test = x_test.reshape((x_test.shape[0], 28, 28, -1))


In [9]:
y_test.shape

(10000, 2)

In [10]:
print ("x_train : %d pics, %d x %d x %d" %x_train.shape)
print ("y_train : %d answers, 1 x %d" %y_train.shape)
print ("x_test : %d pics, %d x %d x %d" %x_test.shape)
print ("y_test : %d answers, 1 x %d" %y_test.shape)

x_train : 60000 pics, 28 x 28 x 1
y_train : 60000 answers, 1 x 2
x_test : 10000 pics, 28 x 28 x 1
y_test : 10000 answers, 1 x 2


In [11]:
model = Sequential()

model.add(Conv2D(kernel_initializer="random_uniform", bias_initializer="zeros", activation="relu", padding="same", filters=3, kernel_size=4,  input_shape=(28, 28, 1), name="1layer"))
model.add(MaxPooling2D((2, 2), padding="same", name="2layer"))
model.add(Flatten(name="3layer"))
model.add(Dense(units=2, activation="relu", name="4layer"))

model.compile(loss="binary_crossentropy", metrics=["acc"], optimizer=Adam())

In [12]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
1layer (Conv2D)              (None, 28, 28, 3)         51        
_________________________________________________________________
2layer (MaxPooling2D)        (None, 14, 14, 3)         0         
_________________________________________________________________
3layer (Flatten)             (None, 588)               0         
_________________________________________________________________
4layer (Dense)               (None, 2)                 1178      
Total params: 1,229
Trainable params: 1,229
Non-trainable params: 0
_________________________________________________________________


In [13]:
model.fit(x_train, y_train, batch_size=64, epochs=20, shuffle=True)

Epoch 1/20
60000/60000 [==============================] - 17s 283us/step - loss: 0.4367 - acc: 0.8186
Epoch 2/20
60000/60000 [==============================] - 16s 271us/step - loss: 0.3305 - acc: 0.8709
Epoch 3/20
60000/60000 [==============================] - 16s 272us/step - loss: 0.3458 - acc: 0.8679
Epoch 4/20
60000/60000 [==============================] - 17s 276us/step - loss: 0.6112 - acc: 0.8110
Epoch 5/20
60000/60000 [==============================] - 17s 283us/step - loss: 0.2993 - acc: 0.8635
Epoch 6/20
60000/60000 [==============================] - 18s 307us/step - loss: 0.2560 - acc: 0.87424s - loss: 0.2607 - acc:  - ETA: 3s -
Epoch 7/20
60000/60000 [==============================] - 17s 291us/step - loss: 0.2719 - acc: 0.8718
Epoch 8/20
60000/60000 [==============================] - 17s 292us/step - loss: 0.2360 - acc: 0.8874
Epoch 9/20
60000/60000 [==============================] - 19s 311us/step - loss: 0.2277 - acc: 0.87992s - loss: 0.22 - ETA: 1s - loss: 
Epoch 10/20

In [14]:
model.evaluate(x_test, y_test)

10000/10000 [==============================] - 3s 258us/step


[0.14489167460426688, 0.8486]

In [15]:
model.evaluate(x_train, y_train)

60000/60000 [==============================] - 16s 270us/step


[0.1563074635763963, 0.8476166666666667]