In [1]:
import os
os.path

<module 'ntpath' from 'C:\\Users\\David\\Anaconda3\\envs\\pygame\\lib\\ntpath.py'>

In [2]:
import arcade

In [3]:
from tensorflow.python.client import device_lib
print (device_lib.list_local_devices())

[name: "/device:CPU:0"
device_type: "CPU"
memory_limit: 268435456
locality {
}
incarnation: 17451859828617696902
]


In [70]:
q=np.array([[1, 2, 3], [4, 5, 6]])
for i in q[1]:
    
    print (i)

False
False
True


In [69]:
a = np.zeros((3, 3, 2))
b = np.ones((3, 3, 2))
for i in a[2, :, 1]==0:
    print (1)
c = np.concatenate((a, b, b, b), axis=2)
print (c.shape)
print (a)
print (b)
print (c)
np.save("a.npy", a)

1
1
1
(3, 3, 8)
[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]
[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]
[[[0. 0. 1. 1. 1. 1. 1. 1.]
  [0. 0. 1. 1. 1. 1. 1. 1.]
  [0. 0. 1. 1. 1. 1. 1. 1.]]

 [[0. 0. 1. 1. 1. 1. 1. 1.]
  [0. 0. 1. 1. 1. 1. 1. 1.]
  [0. 0. 1. 1. 1. 1. 1. 1.]]

 [[0. 0. 1. 1. 1. 1. 1. 1.]
  [0. 0. 1. 1. 1. 1. 1. 1.]
  [0. 0. 1. 1. 1. 1. 1. 1.]]]


In [24]:
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
import keras
import pandas
from keras.datasets import mnist

from keras.models import Sequential
from keras.optimizers import adam
from keras.utils import to_categorical
from keras.layers import Activation, Conv3D, Dense, Flatten, MaxPool3D

In [2]:
(x_train0,y_train), (x_test0, y_test) = mnist.load_data()


In [3]:
print (x_train0.shape)
print (y_train.shape)
print (x_test0.shape)
print (y_test.shape)

(60000, 28, 28)
(60000,)
(10000, 28, 28)
(10000,)


In [4]:
x_train0[0][2][:]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0], dtype=uint8)

In [5]:
x_train=[]
x_test=[]
for i in range(int(60000/4)):
    pic=[x_train0[i][:][:], x_train0[i+1][:][:], x_train0[i+2][:][:], x_train0[i+3][:][:]]
    x_train.append(pic)
for i in range(int(10000/4)):
    pic=[x_test0[i][:][:], x_test0[i+1][:][:], x_test0[i+2][:][:], x_test0[i+3][:][:]]
    x_test.append(pic)

In [6]:
x_train = np.array(x_train)
print (x_train.shape)
x_test = np.array(x_test)
print (x_test.shape)

(15000, 4, 28, 28)
(2500, 4, 28, 28)


In [7]:
x_train=x_train.reshape(15000, 4, 28, 28, 1)
x_test=x_test.reshape(2500, 4, 28, 28, 1)
print (x_train.shape)
print (x_test.shape)

(15000, 4, 28, 28, 1)
(2500, 4, 28, 28, 1)


In [8]:
y_train = y_train[:15000]
y_test = y_test[:2500]

In [9]:
y_train = to_categorical(y_train, 10)
y_test = to_categorical(y_test, 10)

In [10]:
print (y_train.shape, y_test.shape)


(15000, 10) (2500, 10)


In [12]:
model=Sequential()

model.add(Conv3D(activation='relu', filters=3, padding='same', kernel_size=4, input_shape=(4, 28, 28, 1)))
model.add(MaxPool3D(padding='same', pool_size=4))
model.add(Flatten())
model.add(Dense(activation='relu', units=10))

In [13]:
model.compile(loss='mse', metrics=['acc'], optimizer=adam())

In [14]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv3d_1 (Conv3D)            (None, 4, 28, 28, 3)      195       
_________________________________________________________________
max_pooling3d_1 (MaxPooling3 (None, 1, 7, 7, 3)        0         
_________________________________________________________________
flatten_1 (Flatten)          (None, 147)               0         
_________________________________________________________________
dense_1 (Dense)              (None, 10)                1480      
Total params: 1,675
Trainable params: 1,675
Non-trainable params: 0
_________________________________________________________________


In [ ]:
model.fit(x_train, y_train, batch_size=128, epochs=10, shuffle=True)

Epoch 1/10
15000/15000 [==============================] - 233s 16ms/step - loss: 200.7775 - acc: 0.0984
Epoch 2/10
15000/15000 [==============================] - 228s 15ms/step - loss: 1.1592 - acc: 0.1001
Epoch 3/10
15000/15000 [==============================] - 233s 16ms/step - loss: 0.4942 - acc: 0.1007
Epoch 4/10
 2176/15000 [===>..........................] - ETA: 3:18 - loss: 0.2228 - acc: 0.0974

In [ ]:
model.su

In [10]:
a = np.array([np.array([123,1,4,4,322, 12, 12]), np.array([1,2,3,4,4,5,5]), np.array([1,2,3,4,4,5,5])])
max(a[:, 0])

123

In [1]:
x=np.linspace(-100, 100, 2000)
y=np.sqrt(x**2)
z=-np.sqrt(x**2)
plt.plot(x, y)
plt.plot(x, z )
plt.savefig("test.png")

NameError: name 'np' is not defined

In [4]:
ssh ycclab@140.112.55.136


SyntaxError: invalid syntax (<ipython-input-4-04aae370b211>, line 1)

In [6]:
a=1
for i in range(1, 10):
    a*=i
a


362880

In [39]:
arr = np.ndarray(shape=(4, 4))

In [40]:
arr

array([[4.67296746e-307, 1.69121096e-306, 1.95819673e-306,
        8.34441742e-308],
       [1.78022342e-306, 6.23058028e-307, 9.79107872e-307,
        6.89807188e-307],
       [7.56594375e-307, 6.23060065e-307, 1.78021527e-306,
        8.34454050e-308],
       [1.11261027e-306, 1.15706896e-306, 1.33512173e-306,
        1.33504432e-306]])

In [41]:
arr[1, 1] = 3

In [45]:
arr.reshape(-1, 1)

array([[4.67296746e-307],
       [1.69121096e-306],
       [1.95819673e-306],
       [8.34441742e-308],
       [1.78022342e-306],
       [3.00000000e+000],
       [9.79107872e-307],
       [6.89807188e-307],
       [7.56594375e-307],
       [6.23060065e-307],
       [1.78021527e-306],
       [8.34454050e-308],
       [1.11261027e-306],
       [1.15706896e-306],
       [1.33512173e-306],
       [1.33504432e-306]])

In [2]:
import pandas as pd

In [7]:
ssh shanpig8762@eos.ch.ntu.edu.tw

SyntaxError: invalid syntax (<ipython-input-7-bcab5f7a6360>, line 1)

In [7]:
a=True
b=False
if a & (not b):
    print ("sss")

sss


In [14]:
def main(a):
    print ("hello")

In [15]:
if __name__ == "__main__":
    main()

TypeError: main() missing 1 required positional argument: 'a'

In [12]:
main()

hello


In [ ]:
while True:
    old = input("hello")
    if (type(old)==""):
        break

helloda
helloasd
helloTrue


In [10]:
a = np.array([[1., 6., 123., 4., 5.], [6., 7., 8., 9., 10.]])
for i in range(len(a[0])):
    print (max(a[:, i]))
    a[:, i]= a[:, i]/max(a[:, i])

6.0
7.0
123.0
9.0
10.0


In [11]:
a

array([[0.16666667, 0.85714286, 1.        , 0.44444444, 0.5       ],
       [1.        , 1.        , 0.06504065, 1.        , 1.        ]])

In [10]:
import collections
a = [1,2,3,4,5,4,3,2,1,2,2,2]
b = collections.Counter(a)
b

Counter({1: 2, 2: 5, 3: 2, 4: 2, 5: 1})